/**
 * Amazon Product Data Cache
 * Auto-generated by update-amazon-data.js
 * Last updated: 2025-09-29T04:32:31.897Z
 *
 * This is static data served to users - no API calls from public site
 */

export interface CachedAmazonProduct {
  asin: string;
  title?: string;
  price?: {
    amount: number;
    currency: string;
    displayAmount: string;
  } | null;
  imageUrl?: string;
  detailPageUrl: string;
  availability?: string;
  isPrime?: boolean;
  rating?: number;
  reviewCount?: number;
  lastUpdated: string;
}

export const AMAZON_PRODUCT_CACHE: Record<string, CachedAmazonProduct> = {};

export const HELMET_TO_ASIN: Record<string, string> = {
  "GIRO SYNTAX MIPS": "B0CKRYSQ88",
  "SMITH SIGNAL MIPS": "B08WBMM4MG",
  "SMITH ROUTE MIPS": "B08WBLSHBB",
  "GIRO AETHER SPHERICAL": "B07FTSN2QP",
  "BELL Z20 MIPS": "B07JC3Q6PG",
  "BELL Z20 AERO MIPS": "B07JC3Q6PG",
  "POC VENTRAL AIR MIPS": "B09Q5S7BYB",
  "GIRO SYNTHE MIPS": "B017Y92QUQ",
  "GIRO FORAY MIPS": "B07GT7F78H",
  "MET TRENTA MIPS": "B0993F24FM",
  "KASK PROTONE": "B013EYA5OY",
  "SPECIALIZED ALIGN II MIPS": "B07PBQG8QP",
  "BELL DRAFT MIPS": "B07DLHCR2L",
  "GIRO REGISTER MIPS": "B07NQBVD6X",
  "SMITH PERSIST MIPS": "B08G8B8M2G",
  "BONTRAGER RALLY MIPS": "B07P6RJZV5",
  "SCOTT VIVO PLUS MIPS": "B08FBQ8HX3",
  "GIANT PURSUIT": "B08BCRKMFV",
  "LAZER BLADE PLUS MIPS": "B085TCXJ7D",
  "OAKLEY ARO3": "B07QGXZ6G8",
  "KASK MOJITO 3": "B07HRGJ6KL",
  "FOX RACING SPEEDFRAME PRO": "B0988PTB2Z",
  "FOX RACING SPEEDFRAME RS": "B0C83KZQX2",
  "POC CYTAL": "B0FBKCB2L1",
  "GIRO ARIES SPHERICAL": "B0BHXT7LZP",
  "FOX RACING DROPFRAME PRO": "B084DLL36R",
  "FOX RACING CROSSFRAME PRO": "B0BQPYDL2J",
  "TROY LEE DESIGNS A2 MIPS": "B09RMM7QHM",
  "SCOTT CENTRIC PLUS MIPS": "B076MHBNZJ",
  "POC OCTAL X SPIN": "B079YGSVHF",
  "SCOTT ARX PLUS MIPS 2020": "B08PQ6HSJH",
  "SCOTT ARGO PLUS MIPS": "B09G1ZTJLX",
  "TROY LEE DESIGNS FLOWLINE": "B0DXC8QQLY",
  "GIRO ECLIPSE SPHERICAL": "B09VCYLQPX",
  "GIRO TYRANT": "B07YF1CSTC",
  "GIRO MANIFEST SPHERICAL": "B09JC9PK54",
  "GIRO CHRONICLE MIPS": "B07WTWBYCH"
};

export function getCachedProduct(asin: string): CachedAmazonProduct | undefined {
  return AMAZON_PRODUCT_CACHE[asin];
}

export function getHelmetProduct(brand: string, name: string): CachedAmazonProduct | undefined {
  const key = `${brand.toUpperCase()} ${name.toUpperCase()}`;
  const asin = HELMET_TO_ASIN[key];
  return asin ? AMAZON_PRODUCT_CACHE[asin] : undefined;
}
